" ======================
"        Plugins
" ======================
call plug#begin()

Plug 'sainnhe/gruvbox-material'
Plug 'tribela/vim-transparent'
Plug 'sheerun/vim-polyglot'
Plug 'mg979/vim-visual-multi', {'branch': 'master'}
Plug 'machakann/vim-highlightedyank'
Plug 'cofyc/vim-uncrustify'
Plug 'tpope/vim-commentary'
Plug 'takac/vim-hardtime'
Plug 'rhysd/clever-f.vim'
Plug 'tpope/vim-surround'
Plug 'yukimura1227/vim-yazi'
Plug 'wellle/targets.vim'
" Plug 'christoomey/vim-system-copy'
Plug 'tpope/vim-repeat'
Plug 'inkarkat/vim-ReplaceWithRegister'
Plug 'c3lang/editor-plugins', { 'rtp': 'vim' } " Official C3 syntax
Plug 'zah/nim.vim'                        " Official Nim syntax
Plug 'clojure-vim/clojure.vim' " Clojure syntax, matching, and indentation 

call plug#end()
"Plug 'wikitopian/hardmode'
"Plug 'morhetz/gruvbox'
"Plug 'plasticboy/vim-markdown'

augroup uncrustify_maps
  autocmd!
  autocmd FileType c   nnoremap <buffer> <C-f> :call Uncrustify('c')<CR>
  autocmd FileType c   vnoremap <buffer> <C-f> :call RangeUncrustify('c')<CR>
  autocmd FileType cpp nnoremap <buffer> <C-f> :call Uncrustify('cpp')<CR>
  autocmd FileType cpp vnoremap <buffer> <C-f> :call RangeUncrustify('cpp')<CR>
augroup END

" autocmd FileType c,cpp call AutoPairsInit()

"fix problem with st/vim comment if you are not on st
autocmd FocusLost * call system('xclip -selection clipboard -in', @+)
autocmd TextYankPost * call system('xclip -selection clipboard -in', @+)
"If called on a directory then open yazi
autocmd VimEnter * if argc() == 1 && isdirectory(argv(0)) |
  \ call feedkeys(":Yazi\<CR>") |
  \ endif
command! MakeTags !ctags -R .

let g:uncrustify_config_path = expand('~/.config/uncrustify/uncrustify.cfg')
let g:uncrustify_lang_c   = 'c'
let g:uncrustify_lang_cpp = 'cpp'

syntax on
filetype plugin indent on
set nocompatible
set nocursorline
set nocursorcolumn
set number
set ai
set laststatus=0
set tabstop=4
"set linespace=4
set shiftwidth=4
set softtabstop=4
set expandtab
set clipboard=unnamed,unnamedplus
"set noesckeys
set nowrap
set ignorecase
set smartcase
set incsearch
set cinoptions=l1
"set modeline
set autoindent
set autochdir
set termguicolors
set background=dark
if (has("termguicolors"))
  set termguicolors
endif

set signcolumn=yes
set updatetime=300

set list
set listchars=tab:\ \ ,trail:·

set path+=**
set wildmenu

set relativenumber
set undofile
set undodir=~/.vim/filebackups/

set makeprg=just
" =========================
" Buffer-local options
" =========================
setlocal fileformat=unix

" Force to not show flash things at startup
set t_ut=
augroup transparent_fixes
    autocmd!
    autocmd ColorScheme * highlight Normal         guibg=NONE ctermbg=NONE
    autocmd ColorScheme * highlight StatusLine     guibg=NONE ctermbg=NONE guifg=NONE ctermfg=NONE
    autocmd ColorScheme * highlight StatusLineNC   guibg=NONE ctermbg=NONE guifg=NONE ctermfg=NONE
    autocmd ColorScheme * highlight StatusLineTerm   guibg=NONE ctermbg=NONE
    autocmd ColorScheme * highlight StatusLineTermNC guibg=NONE ctermbg=NONE
augroup END
"let g:gruvbox_contrast_dark = 'hard'
"let g:gruvbox_transparent_bg = 1
let g:gruvbox_material_background = 'dark'
let g:gruvbox_material_better_performance = 1
let g:gruvbox_material_transparent_background = 1
colorscheme gruvbox-material

"Bash
let g:is_bash = 1

"Markdown
let g:vim_markdown_folding_disabled = 0   " enable folding
let g:vim_markdown_auto_insert_bullets = 1
let g:vim_markdown_new_list_item_indent = 2
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_conceal = 0

" =========================
" Sessions
" =========================
set sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions

" =========================
" Leader key
" =========================
let mapleader=" "

" =========================
" File detection
" =========================
let g:c_syntax_for_h = 1

" =========================
" Disable default plugins
" =========================
let g:loaded_netrw       = 1
let g:loaded_netrwPlugin= 1
let g:loaded_gzip        = 1
let g:loaded_tar         = 1
let g:loaded_tarPlugin  = 1
let g:loaded_zip        = 1
let g:loaded_zipPlugin  = 1
let g:loaded_tutor      = 1
let g:loaded_tohtml     = 1
let g:loaded_rplugin    = 1
packadd! matchit
let g:undolevels = 1000
let g:highlightedyank_highlight_duration = 100
highlight HighlightedyankRegion ctermbg=0 guibg=#8ec07c

let g:VM_maps = {}
let g:VM_maps["Undo"] = 'u'
let g:VM_maps["Redo"] = '<C-r>'
let g:VM_maps['Exit'] = '<Esc>'

nmap <C-k> <Plug>(VM-Add-Cursor-Up)
nmap <C-j> <Plug>(VM-Add-Cursor-Down)
autocmd BufEnter * if &filetype == "go" | setlocal noexpandtab
autocmd BufNewFile,BufRead ?\+.c3 setf c

"nnoremap d "_d
"vnoremap d "_d
"nnoremap c "_c
"vnoremap c "_c
"vnoremap p "_dP
"nnoremap <leader>d d
"vnoremap <leader>d d
nnoremap <Tab> >>
nnoremap <S-Tab> << 
nnoremap ^ &
nnoremap & ^
nnoremap Y y$
nnoremap gf :e <cfile><CR>
nnoremap <C-b> :term just<CR>
nnoremap <leader>D a<C-R>=strftime("(%Y%m%d-%H%M%S)")<CR><Esc>
"navegate completion with C j and C k
inoremap <expr> <C-j> pumvisible() ? "\<C-n>" : "\<C-j>"
inoremap <expr> <C-k> pumvisible() ? "\<C-p>" : "\<C-k>"
inoremap <C-h> <C-w>
nnoremap <C-t> xp
cnoremap <C-j> <down>
cnoremap <C-k> <up>
nnoremap gt <C-]>
inoremap {<CR> {<CR>}<C-f><Esc>O
" inoremap {<CR> {<CR>}<Esc>O

" st workaround
nmap <Esc>; gcc
vmap <Esc>; gc
nmap <Esc>j :m .+1<CR>==
nmap <Esc>k :m .-2<CR>==
vmap <Esc>j :m '>+1<CR>gv=gv
vmap <Esc>k :m '<-2<CR>gv=gv
" kitty / terminals that send proper M-
" nmap <M-;> gcc
" vmap <M-;> gc
" nnoremap <M-j> :m .+1<CR>==
" nnoremap <M-k> :m .-2<CR>==
" vnoremap <M-j> :m '>+1<CR>gv=gv
" vnoremap <M-k> :m '<-2<CR>gv=gv

function! ToggleTitleCase()
    let save_cursor = getcurpos()
    silent! %s/\<\(\w\)\(\w*\)\>/\u\1\L\2/g
    call setpos('.', save_cursor)
endfunction
command! Uppercasefile call ToggleTitleCase()

if !has('gui_running')
    set ttimeoutlen=10
    let &t_EI = "\<Esc>[2 q" " Normal
    let &t_SI = "\<Esc>[6 q" " Insert
    let &t_SR = "\<Esc>[4 q" " Replace
endif

let g:hardtime_default_on = 1

set fillchars=eob:\ 
