# `sheldon` configuration file
# ----------------------------
shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

[plugins.fast-syntax-highlighting]
github = "z-shell/F-Sy-H"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

#[plugins.autojump]
#github = "wting/autojump"
#apply = ["defer"]
