###################
# Unified Picom Configuration
###################
# corner-radius = 12;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'dwm'",
  "class_g = 'dmenu'"
];

# Animations
animations = (
    {
        triggers = ["close"];
        opacity = {
            curve = "linear";
            duration = 0.04;
            start = "window-raw-opacity-before";
            end = 0;
        };
        shadow-opacity = "opacity";
    },
    {
        triggers = ["open"];
        opacity = {
            curve = "cubic-bezier(0,1,1,1)";
            duration = 0.05;
            start = 0;
            end = "window-raw-opacity";
        };
        offset-x = "(1 - scale-x) / 2 * window-width";
        offset-y = "(1 - scale-y) / 2 * window-height";
        scale-x = {
            curve = "cubic-bezier(0,1.1,1,1)";
            duration = 0.10;
            start = 0.6;
            end = 1;
        };
        scale-y = "scale-x";
        shadow-scale-x = "scale-x";
        shadow-scale-y = "scale-y";
        shadow-offset-x = "offset-x";
        shadow-offset-y = "offset-y";
    }
);

# Fading
fading = true;
fade-in-step = 0.08;
fade-out-step = 0.08;

# Opacity
frame-opacity = 0.8;
inactive-opacity = 0.85;
active-opacity = 1.0;
opacity-rule = [
    "85:class_g = 'Emacs'",
    "85:class_g = 'Bar'",
    "85:class_g = 'Polybar'",
    "70:class_g = 'TelegramDesktop'",
    "90:class_g = 'Joplin'"
];

# Blur
# Kawase Blur Settings (Toggleable)
blur-method = "dual_kawase";
blur-strength = 5;  # Adjust strength as needed
blur-background = true;
blur-background-frame = true;
blur-background-fixed = false;
blur-background-exclude = [
    #"window_type = 'dock'",
    #"window_type = 'desktop'",
    "class_g != 'Emacs' && class_g != 'Bar' && class_g != 'Polybar' && class_g != 'TelegramDesktop' && class_g != 'Joplin' && class_g != 'st-256color'" ,
    # "_GTK_FRAME_EXTENTS@:c"
];

# General Settings
backend = "glx";
vsync = true;
use-damage = false;
detect-rounded-corners = true;
detect-client-opacity = true;
log-level = "info";

# Window Types
wintypes:
{
    normal = { fade = false; shadow = false; };
    desktop = { fade = false; shadow = false; };
    tooltip = { fade = true; shadow = true; opacity = 0.85; focus = true; full-shadow = false; };
    dock = { shadow = false; };
    dnd = { shadow = false; };
    popup_menu = { opacity = 0.9; };
    dropdown_menu = { opacity = 0.9; };
};
