#!/bin/sh

if [ -z "$1" ]; then
    exit 1
fi

export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
fi
response=$(tgpt --provider sky -q "$*" 2>/dev/null)
/usr/bin/notify-send "AI Chat Answer" "$response" -i dialog-information
