#!/bin/sh

DMENU="dmenu -c -l 6 -h 40"

choice=$(printf "US\nEspañol\nFrançais\nFrançaisQY\nDvorak\nColemak\n" | $DMENU)

case "$choice" in
  US)
    setxkbmap us
    ;;
  Español)
    setxkbmap latam
    ;;
  Français|FrançaisAZ)
    setxkbmap fr
    ;;
  FrançaisQY)
    setxkbmap fr us
    ;;
  Dvorak)
    setxkbmap us dvorak
    ;;
  Colemak)
    setxkbmap us colemak
    ;;
esac
